// Tests for the D1 binding seam in the wrangler.toml patcher.
//
// D1 mirrors the KV/R2 patch+append machinery, so comment preservation is the
// load-bearing property here too. Every patch/append asserts the surrounding
// comments survive the edit. D1 is OFF by default — these tests exercise the
// opt-in primitives a pack (bindings.d1=true) or `flint add d1` invokes.

import { afterEach, describe, expect, it } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  appendD1DatabaseBlock,
  patchD1Database,
  readWranglerToml,
} from '../../src/cloudflare/wrangler-toml.js';
import { extractD1IdFromOutput } from '../../src/commands/configure.js';

const SAMPLE = `# Generated by Flint. Edit freely.
name = "myapp"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-14"

# KV namespace for content.
[[kv_namespaces]]
binding = "CONTENT_KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID"

# D1 database for relational data.
[[d1_databases]]
binding = "DB"
database_name = "myapp-db"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
`;

function setupRepo(contents: string): { dir: string; cleanup: () => void } {
  const dir = mkdtempSync(join(tmpdir(), 'flint-d1-'));
  writeFileSync(join(dir, 'wrangler.toml'), contents, 'utf8');
  return { dir, cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

const REAL_UUID = 'abcd1234-5678-90ab-cdef-1234567890ab';

describe('readWranglerToml (D1)', () => {
  let repo: ReturnType<typeof setupRepo>;
  afterEach(() => repo?.cleanup());

  it('parses [[d1_databases]] blocks', () => {
    repo = setupRepo(SAMPLE);
    const doc = readWranglerToml(repo.dir);
    expect(doc.d1_databases).toHaveLength(1);
    expect(doc.d1_databases[0]!.binding).toBe('DB');
    expect(doc.d1_databases[0]!.database_name).toBe('myapp-db');
  });

  it('returns an empty array when no D1 block is present (backward compat)', () => {
    repo = setupRepo('name = "x"\n');
    const doc = readWranglerToml(repo.dir);
    expect(doc.d1_databases).toEqual([]);
  });
});

describe('patchD1Database', () => {
  let repo: ReturnType<typeof setupRepo>;
  afterEach(() => repo?.cleanup());

  it('replaces database_id for an existing binding', () => {
    repo = setupRepo(SAMPLE);
    const doc = readWranglerToml(repo.dir);
    const patched = patchD1Database(doc, 'DB', { database_id: REAL_UUID });
    expect(patched.raw).toContain(`database_id = "${REAL_UUID}"`);
    expect(patched.raw).not.toContain('REPLACE_WITH_D1_DATABASE_ID');
    expect(patched.d1_databases[0]!.database_id).toBe(REAL_UUID);
  });

  it('preserves all surrounding comments', () => {
    repo = setupRepo(SAMPLE);
    const doc = readWranglerToml(repo.dir);
    const patched = patchD1Database(doc, 'DB', { database_id: REAL_UUID });
    expect(patched.raw).toContain('# Generated by Flint. Edit freely.');
    expect(patched.raw).toContain('# KV namespace for content.');
    expect(patched.raw).toContain('# D1 database for relational data.');
  });

  it('throws a clear error when the binding does not exist', () => {
    repo = setupRepo(SAMPLE);
    const doc = readWranglerToml(repo.dir);
    expect(() => patchD1Database(doc, 'NOPE', { database_id: REAL_UUID })).toThrow(
      /\[\[d1_databases\]\] block with binding="NOPE"/,
    );
  });
});

describe('appendD1DatabaseBlock', () => {
  let repo: ReturnType<typeof setupRepo>;
  afterEach(() => repo?.cleanup());

  it('appends a new [[d1_databases]] block with a placeholder id', () => {
    repo = setupRepo('name = "myapp"\n');
    const doc = readWranglerToml(repo.dir);
    const next = appendD1DatabaseBlock(doc, { binding: 'ANALYTICS_DB', database_name: 'myapp-analytics' });
    expect(next.d1_databases).toHaveLength(1);
    expect(next.d1_databases[0]!.binding).toBe('ANALYTICS_DB');
    expect(next.raw).toContain('[[d1_databases]]\nbinding = "ANALYTICS_DB"');
    expect(next.raw).toContain('database_name = "myapp-analytics"');
    expect(next.raw).toContain('REPLACE_WITH_D1_DATABASE_ID');
  });

  it('keeps existing blocks + comments intact when appending', () => {
    repo = setupRepo(SAMPLE);
    const doc = readWranglerToml(repo.dir);
    const next = appendD1DatabaseBlock(doc, { binding: 'SECOND_DB', database_name: 'myapp-second' });
    expect(next.d1_databases).toHaveLength(2);
    expect(next.raw).toContain('# KV namespace for content.');
    expect(next.raw).toContain('binding = "DB"');
    expect(next.raw).toContain('binding = "SECOND_DB"');
  });

  it('emits an optional comment above the new block', () => {
    repo = setupRepo('name = "x"\n');
    const doc = readWranglerToml(repo.dir);
    const next = appendD1DatabaseBlock(doc, {
      binding: 'DB',
      database_name: 'x-db',
      comment: 'Pack-declared D1.\nProvision via flint configure --d1.',
    });
    expect(next.raw).toMatch(/# Pack-declared D1\.\n# Provision via flint configure --d1\.\n\[\[d1_databases\]\]/);
  });
});

describe('extractD1IdFromOutput', () => {
  it('extracts a uuid from a JSON-shaped output', () => {
    expect(extractD1IdFromOutput(`{"uuid":"${REAL_UUID}","name":"x"}`)).toBe(REAL_UUID);
  });

  it('extracts a uuid from a TOML-snippet output', () => {
    expect(extractD1IdFromOutput(`database_id = "${REAL_UUID}"`)).toBe(REAL_UUID);
  });

  it('extracts a bare uuid from a sentence', () => {
    expect(
      extractD1IdFromOutput(`✅ Successfully created DB 'x' in region ENAM\n  ${REAL_UUID}`),
    ).toBe(REAL_UUID);
  });

  it('returns null when no uuid is present', () => {
    expect(extractD1IdFromOutput('no id here')).toBeNull();
  });
});
