// Tests for the in-place wrangler.toml patcher.
//
// Comment preservation is the load-bearing property here (acceptance
// criterion 3). Every patch / append test asserts that the original
// comments are still present in the output text.

import { afterEach, describe, expect, it } from 'vitest';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  appendKvNamespaceBlock,
  appendR2BucketBlock,
  diffTomlText,
  patchKvNamespace,
  patchR2Bucket,
  readWranglerToml,
  WranglerTomlNotFoundError,
  WranglerTomlParseError,
  writeWranglerToml,
} from '../../src/cloudflare/wrangler-toml.js';

const SAMPLE_WITH_COMMENTS = `# Generated by Flint. Edit freely.
name = "myapp"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-14"
compatibility_flags = ["nodejs_compat"]

# KV namespace for content metadata, indexes, rate-limit counters.
# preview_id reuses the same namespace so local wrangler pages dev
# sees the same data.
[[kv_namespaces]]
binding = "CONTENT_KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_KV_NAMESPACE_ID"

# R2 bucket for media uploads.
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "myapp-media"
`;

function setupRepoWithToml(contents: string): { dir: string; cleanup: () => void } {
  const dir = mkdtempSync(join(tmpdir(), 'flint-wt-'));
  writeFileSync(join(dir, 'wrangler.toml'), contents, 'utf8');
  return {
    dir,
    cleanup: () => rmSync(dir, { recursive: true, force: true }),
  };
}

describe('readWranglerToml', () => {
  let repo: ReturnType<typeof setupRepoWithToml>;
  afterEach(() => repo?.cleanup());

  it('parses name + bindings from a sample document', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    expect(doc.name).toBe('myapp');
    expect(doc.kv_namespaces).toHaveLength(1);
    expect(doc.kv_namespaces[0]!.binding).toBe('CONTENT_KV');
    expect(doc.r2_buckets).toHaveLength(1);
    expect(doc.r2_buckets[0]!.binding).toBe('MEDIA_BUCKET');
    expect(doc.r2_buckets[0]!.bucket_name).toBe('myapp-media');
  });

  it('preserves the raw text including all comments', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    expect(doc.raw).toContain('# Generated by Flint. Edit freely.');
    expect(doc.raw).toContain('# KV namespace for content metadata');
    expect(doc.raw).toContain('# R2 bucket for media uploads.');
  });

  it('throws WranglerTomlNotFoundError when wrangler.toml is missing', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    rmSync(join(repo.dir, 'wrangler.toml'));
    expect(() => readWranglerToml(repo.dir)).toThrow(WranglerTomlNotFoundError);
  });

  it('throws WranglerTomlParseError on invalid TOML', () => {
    repo = setupRepoWithToml('name = "broken\n[[unclosed]');
    expect(() => readWranglerToml(repo.dir)).toThrow(WranglerTomlParseError);
  });
});

describe('patchKvNamespace', () => {
  let repo: ReturnType<typeof setupRepoWithToml>;
  afterEach(() => repo?.cleanup());

  it('replaces id and preview_id for an existing binding', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    const patched = patchKvNamespace(doc, 'CONTENT_KV', {
      id: 'aaaabbbbccccdddd1111222233334444',
      preview_id: 'aaaabbbbccccdddd1111222233334444',
    });
    expect(patched.raw).toContain('id = "aaaabbbbccccdddd1111222233334444"');
    expect(patched.raw).toContain('preview_id = "aaaabbbbccccdddd1111222233334444"');
    expect(patched.raw).not.toContain('REPLACE_WITH_KV_NAMESPACE_ID');
  });

  it('preserves comments after patching', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    const patched = patchKvNamespace(doc, 'CONTENT_KV', { id: 'abc123abc123abc1' });
    expect(patched.raw).toContain('# Generated by Flint. Edit freely.');
    expect(patched.raw).toContain('# KV namespace for content metadata');
    expect(patched.raw).toContain('# R2 bucket for media uploads.');
  });

  it('throws a clear error when binding does not exist', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    expect(() => patchKvNamespace(doc, 'NOPE_KV', { id: 'x' })).toThrow(
      /\[\[kv_namespaces\]\] block with binding="NOPE_KV"/,
    );
  });

  it('re-parsing after patch leaves the parsed view in sync', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    const patched = patchKvNamespace(doc, 'CONTENT_KV', {
      id: 'newid000000000000000000000000ab',
    });
    expect(patched.kv_namespaces[0]!.id).toBe('newid000000000000000000000000ab');
  });
});

describe('patchR2Bucket', () => {
  let repo: ReturnType<typeof setupRepoWithToml>;
  afterEach(() => repo?.cleanup());

  it('replaces bucket_name', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    const patched = patchR2Bucket(doc, 'MEDIA_BUCKET', { bucket_name: 'newbucketname' });
    expect(patched.raw).toContain('bucket_name = "newbucketname"');
    expect(patched.raw).not.toContain('"myapp-media"');
    expect(patched.r2_buckets[0]!.bucket_name).toBe('newbucketname');
  });

  it('preserves the R2 block comment', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    const patched = patchR2Bucket(doc, 'MEDIA_BUCKET', { bucket_name: 'x-y' });
    expect(patched.raw).toContain('# R2 bucket for media uploads.');
  });
});

describe('appendKvNamespaceBlock', () => {
  let repo: ReturnType<typeof setupRepoWithToml>;
  afterEach(() => repo?.cleanup());

  it('appends a new [[kv_namespaces]] block with default placeholders', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    const next = appendKvNamespaceBlock(doc, { binding: 'CACHE_KV' });
    expect(next.kv_namespaces).toHaveLength(2);
    expect(next.kv_namespaces.find((k) => k.binding === 'CACHE_KV')).toBeDefined();
    expect(next.raw).toContain('[[kv_namespaces]]\nbinding = "CACHE_KV"');
    expect(next.raw).toContain('REPLACE_WITH_KV_NAMESPACE_ID');
  });

  it('emits the optional comment above the new block', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    const next = appendKvNamespaceBlock(doc, {
      binding: 'CACHE_KV',
      comment: 'Multi-line\nblock comment',
    });
    expect(next.raw).toMatch(/# Multi-line\n# block comment\n\[\[kv_namespaces\]\]/);
  });

  it('keeps existing kv_namespaces blocks and their comments intact', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    const next = appendKvNamespaceBlock(doc, { binding: 'CACHE_KV' });
    expect(next.raw).toContain('# KV namespace for content metadata');
    expect(next.raw).toContain('binding = "CONTENT_KV"');
  });
});

describe('appendR2BucketBlock', () => {
  let repo: ReturnType<typeof setupRepoWithToml>;
  afterEach(() => repo?.cleanup());

  it('appends a new [[r2_buckets]] block with bucket_name', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    const next = appendR2BucketBlock(doc, {
      binding: 'BACKUPS',
      bucket_name: 'myapp-backups',
    });
    expect(next.r2_buckets).toHaveLength(2);
    expect(next.r2_buckets.find((b) => b.binding === 'BACKUPS')?.bucket_name).toBe(
      'myapp-backups',
    );
    expect(next.raw).toContain('binding = "BACKUPS"');
  });
});

describe('writeWranglerToml', () => {
  let repo: ReturnType<typeof setupRepoWithToml>;
  afterEach(() => repo?.cleanup());

  it('persists the current raw text to disk', () => {
    repo = setupRepoWithToml(SAMPLE_WITH_COMMENTS);
    const doc = readWranglerToml(repo.dir);
    const patched = patchKvNamespace(doc, 'CONTENT_KV', { id: 'newid12345678abcd' });
    writeWranglerToml(repo.dir, patched);
    const onDisk = readFileSync(join(repo.dir, 'wrangler.toml'), 'utf8');
    expect(onDisk).toContain('newid12345678abcd');
    expect(onDisk).toContain('# Generated by Flint. Edit freely.');
  });
});

describe('diffTomlText', () => {
  it('returns "(no changes)" when before == after', () => {
    expect(diffTomlText('a\nb\n', 'a\nb\n')).toBe('(no changes)');
  });

  it('flags an added line', () => {
    const out = diffTomlText('a\nb\n', 'a\nb\nc\n');
    expect(out).toContain('+ c');
  });

  it('flags a replaced line as - then +', () => {
    const out = diffTomlText('a\nb\nc\n', 'a\nB\nc\n');
    expect(out).toContain('- b');
    expect(out).toContain('+ B');
  });
});
