// Integration coverage for `flint add kv|r2|secret`.
//
// Smoke checklist mapping (from .agent/SMOKE-2026-05-14.md):
//   - Step 5: `flint add kv CACHE_KV --yes --no-provision` — appends
//             [[kv_namespaces]] without duplicating the existing block
//   - Step 6: `flint add r2 MEDIA_R2 --yes --no-provision` — appends
//             [[r2_buckets]] with auto-derived bucket_name
//   - Step 7: `flint add secret STRIPE_SECRET_KEY --yes --no-provision` —
//             documents stub in .dev.vars.example; does NOT create
//             .dev.vars (disk-free secret invariant)
//
// Harness notes:
//   - We seed a minimal wrangler.toml directly rather than running
//     `flint init` first. That keeps each test fast (~150ms vs ~1.5s for
//     init+add) and isolates the `add` surface from init's variant
//     templates. (init.spec.ts already covers the init path end-to-end.)
//   - `--no-provision` skips the wrangler invocation; `--yes` skips the
//     interactive prompts. Both required for non-TTY child execution.

import { afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { existsSync } from 'node:fs';
import {
  CLI_ENTRY,
  createTempRepo,
  readRepoFile,
  repoFileExists,
  runFlint,
  writeRepoFile,
  type TempRepo,
} from './_harness.js';

// Minimal wrangler.toml mirroring what `flint init --variant pages-functions`
// would produce. We include the CONTENT_KV block so smoke step 5's
// "does-not-duplicate" check has something to detect duplication against.
const STARTER_WRANGLER_TOML = `# Generated by Flint (test fixture).
name = "flint-smoke"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-14"
compatibility_flags = ["nodejs_compat"]

# KV namespace for content, waitlist entries, rate-limit counters.
[[kv_namespaces]]
binding = "CONTENT_KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_KV_NAMESPACE_ID"
`;

describe('flint add (integration)', () => {
  beforeAll(() => {
    if (!existsSync(CLI_ENTRY)) {
      throw new Error(`Build artifact missing: ${CLI_ENTRY}. Run npm run build.`);
    }
  });

  let repo: TempRepo;

  beforeEach(() => {
    repo = createTempRepo();
    writeRepoFile(repo, 'wrangler.toml', STARTER_WRANGLER_TOML);
  });

  afterEach(() => {
    repo.cleanup();
  });

  // ── KV ──────────────────────────────────────────────────────────────────

  it('smoke 5: flint add kv CACHE_KV appends a [[kv_namespaces]] block', () => {
    const res = runFlint(['add', 'kv', 'CACHE_KV', '--yes', '--no-provision'], {
      cwd: repo.dir,
    });

    expect(res.status, `exit:${res.status}\nstdout:${res.stdout}\nstderr:${res.stderr}`).toBe(0);
    const toml = readRepoFile(repo, 'wrangler.toml');
    expect(toml).toContain('binding = "CACHE_KV"');
    expect(toml).toContain('REPLACE_WITH_KV_NAMESPACE_ID');
    // Original CONTENT_KV block must still be present.
    expect(toml).toContain('binding = "CONTENT_KV"');
  });

  it('smoke 5: flint add kv does NOT duplicate an existing binding', () => {
    const res = runFlint(['add', 'kv', 'CONTENT_KV', '--yes', '--no-provision'], {
      cwd: repo.dir,
    });
    expect(res.status).toBe(0);
    const toml = readRepoFile(repo, 'wrangler.toml');
    const occurrences = (toml.match(/binding = "CONTENT_KV"/g) ?? []).length;
    expect(occurrences, 'CONTENT_KV was duplicated').toBe(1);
  });

  // ── R2 ──────────────────────────────────────────────────────────────────

  it('smoke 6: flint add r2 MEDIA_R2 appends with auto-derived bucket_name', () => {
    const res = runFlint(['add', 'r2', 'MEDIA_R2', '--yes', '--no-provision'], {
      cwd: repo.dir,
    });

    expect(res.status, `exit:${res.status}\nstdout:${res.stdout}\nstderr:${res.stderr}`).toBe(0);
    const toml = readRepoFile(repo, 'wrangler.toml');
    expect(toml).toContain('[[r2_buckets]]');
    expect(toml).toContain('binding = "MEDIA_R2"');
    // Bucket name normalization: project-name + binding, lowercase-dashed.
    expect(toml).toContain('bucket_name = "flint-smoke-media-r2"');
  });

  it('smoke 6: flint add r2 preserves the original [[kv_namespaces]] block', () => {
    const res = runFlint(['add', 'r2', 'MEDIA_R2', '--yes', '--no-provision'], {
      cwd: repo.dir,
    });
    expect(res.status).toBe(0);
    const toml = readRepoFile(repo, 'wrangler.toml');
    expect(toml).toContain('binding = "CONTENT_KV"');
    expect(toml).toContain('binding = "MEDIA_R2"');
  });

  // ── Secret ──────────────────────────────────────────────────────────────

  it('smoke 7: flint add secret writes a documented stub to .dev.vars.example', () => {
    const res = runFlint(
      ['add', 'secret', 'STRIPE_SECRET_KEY', '--yes', '--no-provision'],
      { cwd: repo.dir },
    );

    expect(res.status, `exit:${res.status}\nstdout:${res.stdout}\nstderr:${res.stderr}`).toBe(0);

    expect(repoFileExists(repo, '.dev.vars.example')).toBe(true);
    const example = readRepoFile(repo, '.dev.vars.example');
    expect(example).toContain('STRIPE_SECRET_KEY=');
    // The stub line carries a comment pointing at how to set the secret
    // (per smoke step 7 — "inline comment pointing at `wrangler pages
    // secret put` and `flint configure --secrets`").
    expect(example).toMatch(/wrangler pages secret put|flint configure --secrets/);
  });

  it('smoke 7: flint add secret does NOT create .dev.vars (disk-free invariant)', () => {
    // This is the v0.1 security invariant — secrets never land on disk
    // unless the user explicitly opts in with --write-to-dev-vars.
    const res = runFlint(
      ['add', 'secret', 'STRIPE_SECRET_KEY', '--yes', '--no-provision'],
      { cwd: repo.dir },
    );
    expect(res.status).toBe(0);
    expect(
      repoFileExists(repo, '.dev.vars'),
      '.dev.vars MUST NOT be created by `add secret --no-provision`',
    ).toBe(false);
  });

  it('smoke 7: flint add secret normalizes the name to UPPER_SNAKE_CASE', () => {
    const res = runFlint(
      ['add', 'secret', 'stripe-secret-key', '--yes', '--no-provision'],
      { cwd: repo.dir },
    );
    expect(res.status).toBe(0);
    const example = readRepoFile(repo, '.dev.vars.example');
    expect(example).toContain('STRIPE_SECRET_KEY=');
  });
});
