// Integration coverage for the wrangler.toml patcher.
//
// Smoke checklist mapping (from .agent/SMOKE-2026-05-14.md):
//   - Step 9 (CRITICAL): adding a [[r2_buckets]] block via `flint add r2`
//             must preserve user-authored comments verbatim at their
//             original line positions. The smoke report calls this out as
//             the "v0.2 load-bearing test."
//
// Why this rates its own spec rather than living in add.spec.ts:
//   - Comment preservation is the central reason Flint ships a hand-
//     rolled patcher instead of round-tripping through smol-toml. Every
//     v0.5 surface that mutates wrangler.toml (more `add` subcommands,
//     the `upgrade` command, the `configure` writeback) has to honor the
//     same invariant. Keeping this assertion isolated makes the
//     load-bearing test easy to find and re-use.
//   - Spawning the bin (rather than calling the patcher directly) closes
//     the gap between "patcher works in unit tests" and "patcher works
//     when invoked through the CLI pipeline" — i.e. it catches any
//     accidental double-parse or re-serialization step inserted upstream
//     of the patcher.

import { afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { existsSync } from 'node:fs';
import {
  CLI_ENTRY,
  createTempRepo,
  readRepoFile,
  runFlint,
  writeRepoFile,
  type TempRepo,
} from './_harness.js';

// A wrangler.toml with explicit, *targetable* user comments. We give them
// a unique marker so we can both (a) find them post-write and (b) prove
// the patcher didn't shuffle them. Mirrors the smoke step 9 setup which
// inserted `# CUSTOM_MARKER_COMMENT_DO_NOT_DROP_a3f9` at line 3.
const TOML_WITH_USER_COMMENT = `# Generated by Flint (test fixture).
name = "flint-smoke"
# CUSTOM_MARKER_COMMENT_DO_NOT_DROP_a3f9
pages_build_output_dir = "dist"
compatibility_date = "2026-05-14"
compatibility_flags = ["nodejs_compat"]

# Block-attached comment — should remain glued to CONTENT_KV.
[[kv_namespaces]]
binding = "CONTENT_KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_KV_NAMESPACE_ID"
`;

describe('flint add r2 — wrangler.toml comment preservation (integration)', () => {
  beforeAll(() => {
    if (!existsSync(CLI_ENTRY)) {
      throw new Error(`Build artifact missing: ${CLI_ENTRY}. Run npm run build.`);
    }
  });

  let repo: TempRepo;

  beforeEach(() => {
    repo = createTempRepo();
    writeRepoFile(repo, 'wrangler.toml', TOML_WITH_USER_COMMENT);
  });

  afterEach(() => {
    repo.cleanup();
  });

  it('smoke 9: flint add r2 preserves a user comment at its original line position', () => {
    const res = runFlint(['add', 'r2', 'ANOTHER_R2', '--yes', '--no-provision'], {
      cwd: repo.dir,
    });
    expect(
      res.status,
      `exit:${res.status}\nstdout:${res.stdout}\nstderr:${res.stderr}`,
    ).toBe(0);

    const after = readRepoFile(repo, 'wrangler.toml');
    const beforeLines = TOML_WITH_USER_COMMENT.split('\n');
    const afterLines = after.split('\n');

    // The custom marker comment was originally at line 3 (index 2).
    const markerLine = '# CUSTOM_MARKER_COMMENT_DO_NOT_DROP_a3f9';
    const originalIndex = beforeLines.indexOf(markerLine);
    const afterIndex = afterLines.indexOf(markerLine);
    expect(originalIndex, 'fixture mismatch — marker not at expected line').toBe(2);
    expect(afterIndex, `marker comment lost or moved (after: ${afterIndex})`).toBe(
      originalIndex,
    );
  });

  it('smoke 9: flint add r2 only appends to the tail, never rewrites the head', () => {
    const res = runFlint(['add', 'r2', 'ANOTHER_R2', '--yes', '--no-provision'], {
      cwd: repo.dir,
    });
    expect(res.status).toBe(0);

    const after = readRepoFile(repo, 'wrangler.toml');
    // Everything in TOML_WITH_USER_COMMENT before the [[r2_buckets]]
    // append point should be byte-identical in the rewritten file.
    expect(
      after.startsWith(TOML_WITH_USER_COMMENT),
      `head changed:\n--- before ---\n${TOML_WITH_USER_COMMENT}\n--- after head ---\n${after.slice(0, TOML_WITH_USER_COMMENT.length)}`,
    ).toBe(true);
  });

  it('smoke 9: the block-attached comment stays glued to its [[kv_namespaces]] block', () => {
    const res = runFlint(['add', 'r2', 'ANOTHER_R2', '--yes', '--no-provision'], {
      cwd: repo.dir,
    });
    expect(res.status).toBe(0);

    const after = readRepoFile(repo, 'wrangler.toml');
    const lines = after.split('\n');
    const commentIdx = lines.findIndex(
      (l) => l === '# Block-attached comment — should remain glued to CONTENT_KV.',
    );
    expect(commentIdx, 'block-attached comment lost').toBeGreaterThanOrEqual(0);
    // The line immediately after should still be the [[kv_namespaces]] header.
    expect(lines[commentIdx + 1]).toBe('[[kv_namespaces]]');
  });

  it('smoke 9: the new [[r2_buckets]] block appears at the tail of the file', () => {
    const res = runFlint(['add', 'r2', 'ANOTHER_R2', '--yes', '--no-provision'], {
      cwd: repo.dir,
    });
    expect(res.status).toBe(0);

    const after = readRepoFile(repo, 'wrangler.toml');
    // The new block is appended somewhere after the existing content,
    // never inserted into the middle.
    const r2HeaderIdx = after.indexOf('[[r2_buckets]]');
    const kvHeaderIdx = after.indexOf('[[kv_namespaces]]');
    expect(r2HeaderIdx).toBeGreaterThan(-1);
    expect(r2HeaderIdx).toBeGreaterThan(kvHeaderIdx);
    expect(after).toContain('binding = "ANOTHER_R2"');
  });
});
